### ISSUE TITLE
Missing icon in DreamTime 1.6.4

### ISSUE THREAD

**Issue by ale5000-git** [opendreamnet/dreamtime#247]
**Describe the bug**
The icon of Waifu2X in the About section doesn't work

**To Reproduce**
1. Go to the 'About' section
2. See the missing icon of Waifu2X

**Expected behavior**
Load the icon

**Enviroment (please complete the following information):**
 - DreamTime Version 1.6.4
 - Windows 10 21H1
 - RAM: 8 GB
 - CPU: Intel(R) Core(TM) i7-6500U CPU
 - GPU: Intel(R) HD Graphics 520 + NVIDIA GeForce 920MX

**Comment by kolessios** [comment]
Notice: DreamTime is no longer in development and any problems may take months to fix, to visit our new project that generates higher quality nudes visit [SukebeZone+](https://www.sukebezone.com).
