### ISSUE TITLE
Stuck on Checkpoints 0.0.1

### ISSUE THREAD

**Issue by kivawmax** [opendreamnet/dreamtime#260]
**Describe the bug**
Just downloaded the app, installed the latest version of update. And got stuck on downloading the Checkpoints 0.0.1,continuously stuck under than 1%

**To Reproduce**
1. After downloading the latest version of update
2. Press install
3. And stuck

**Expected behavior**
The progress bar should be progressing rather quickly

**Screenshots**
![image](https://user-images.githubusercontent.com/93880399/140704390-99b97f23-b375-4c50-aff7-d47bb6b960e3.png)

**Enviroment (please complete the following information):**
 - DreamTime Version [1.6.4]
 - OS: [ Windows 10 1803]
 - RAM: [ 8 GB]
 - CPU: [ Ryzen 5 2600]
 - GPU: [ RTX 2070 8 GB VRAM]

**Additional information**
Add any other information about the problem here.

**Comment by mhmale** [comment]
i have that bug too
 how can i skip

**Comment by KeterSCP** [comment]
It is not stuck, but for some reason progress bar value is not multiplied by 100. So for example when you see 0.157 it is actually 15.7%

**Comment by DJboutit** [comment]
I am still having the same problem download will always freeze

**Comment by kolessios** [comment]
This is an old problem, but anyway, it should have been fixed by now. 

Notice: DreamTime is no longer in development and any problems may take months to fix, to visit our new project that generates higher quality nudes visit [SukebeZone+](https://www.sukebezone.com).
