### ISSUE TITLE
Dreampower Nvedia installation inssue on popos (linux)

### ISSUE THREAD

**Issue by AnkurSaini07** [opendreamnet/dreamtime#281]
**Describe the bug**
I am trying to install Dreamtime but I am stuck at the installation process of DreamPower,
i am using popos and have rtx 3070  gpu, on Dreampower instalation screen i select Nvidia GPU in device type dropdown and on clicking install button i get the following error.

![1](https://user-images.githubusercontent.com/33354822/147845065-e551c322-342b-4e40-8e4e-4fb6c75e0220.png)

![2](https://user-images.githubusercontent.com/33354822/147845072-cca18986-efe5-4ae7-9163-4cbff68efd23.png)

**To Reproduce**
1. Select Nvidia GPU in device type dropdown and press install button.(Dreampower v1.3 installation page).

**Enviroment (please complete the following information):**
 - DreamTime Version [e.g. 1.6.4]
 - OS: [e.g. PopOs 21.10]
 - RAM: [e.g. 32 GB]
 - CPU: [e.g. Ryzen 9 3900xt]
 - GPU: [e.g. RTX 3070 8 GB VRAM]

**Comment by kolessios** [comment]
If I remember correctly it has to do with some problem detecting locations in Linux. It is recommended to install the components manually: https://www.dreamtime.tech/docs/guide/components

Notice: DreamTime is no longer in development and any problems may take months to fix, to visit our new project that generates higher quality nudes visit [SukebeZone+](https://www.sukebezone.com).
