### ISSUE TITLE
INTERNAL ERROR!

### ISSUE THREAD

**Issue by ll321123** [opendreamnet/dreamtime#294]
INTERNAL ERROR!
DreamTime has not been able to verify that DreamPower works correctly, please fix this issue before continuing. Visit the website with the most common problems or our forum for technical support.

Error: spawn D:\mod\DreamTime\dreampower ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by kolessios** [comment]
DreamTime cannot find DreamPower in the selected location, the easiest way is to reinstall.

Notice: DreamTime is no longer in development and any problems may take months to fix, to visit our new project that generates higher quality nudes visit [SukebeZone+](https://www.sukebezone.com).
