### ISSUE TITLE
The nudes look horiffic

### ISSUE THREAD

**Issue by BoiRayn** [opendreamnet/dreamtime#301]
When I try to make a fake nude, Its always buggy. The breast is glitched, the vagina is ruined. Its just ruined. Any tips on how to make my deep fakes better?

**Comment by notBradPitt** [comment]
This is not a bug, the model is based on DeepNude released 2-3 years ago which was taken down shortly after it was released. Either you aren't selecting the appropriate areas or the model is simply incapable. 99% of those realistic fake nudes you see on internet have gone through Photoshop postprocessing

**Comment by kolessios** [comment]
Visit: https://www.dreamtime.tech/docs/guide/custom-masks

Notice: DreamTime is no longer in development and any problems may take months to fix, to visit our new project that generates higher quality nudes visit [SukebeZone+](https://www.sukebezone.com).
