### ISSUE TITLE
{ERROR} The final result is not a valid image file.

### ISSUE THREAD

**Issue by N3RD12** [opendreamnet/dreamtime#306]
[ERROR] Something gone wrong writing C:\Users\PC PRFOJE��O\AppData\Roaming\dreamtime\Pictures\Uncategorized\unnamed-low-res-scal-RUN1-1650569114038-dreamtime.png image file. The final result is not a valid image file.

**Comment by kolessios** [comment]
Use the portable version, your user name "PC PRFOJE��O" is causing the problem.

Notice: DreamTime is no longer in development and any problems may take months to fix, to visit our new project that generates higher quality nudes visit [SukebeZone+](https://www.sukebezone.com).
