### ISSUE TITLE
blank window on launch

### ISSUE THREAD

**Issue by aroi69** [opendreamnet/dreamtime#307]
**Describe the bug**
When i launch Dreamtime only a empty window appears

**To Reproduce**
1. install dreamtime
2. Open Dreamtime
3. see empty window

**Expected behavior**
it should open normaly

**Screenshots**
![grafik](https://user-images.githubusercontent.com/104720021/166144754-fe77fe34-8827-462f-a016-d17e296e2a6a.png)

**Enviroment (please complete the following information):**
 - DreamTime Version 1.6.4
 - OS: Windows 11
 - RAM: 16GB
 - CPU: Ryzen 5 3600
 - GPU: RTX 2070 Super
 
**Additional information**
I looked at the logs and they said something about being unable to connect to a server on port 3000

[main.log](https://github.com/opendreamnet/dreamtime/files/8598832/main.log)

**Comment by kolessios** [comment]
The version you installed has been compiled as "In Development" and therefore is requesting the NuxtJS server to present the content.

If you are a developer I recommend you visit the [documentation](https://www.dreamtime.tech/docs/advanced/development) to learn how to build the project.

If not, please download and install the version we offer on the official website https://www.dreamtime.tech/

Notice: DreamTime is no longer in development and any problems may take months to fix, to visit our new project that generates higher quality nudes visit [SukebeZone+](https://www.sukebezone.com).
