### ISSUE TITLE
LogEvent: Github has returned that there are no releases!

### ISSUE THREAD

**Issue by caj4** [opendreamnet/dreamtime#323]
**Describe the bug**
Installing components does not work, due to an error.

```
LogEvent: Github has returned that there are no releases!
    at Object._fetchReleases (file:///snap/dreamtimetech/22/resources/app.asar/dist/assets/1575670.js:1:94148)
    at async Object.setup (file:///snap/dreamtimetech/22/resources/app.asar/dist/assets/1575670.js:1:92911)
    at async Object.init (file:///snap/dreamtimetech/22/resources/app.asar/dist/assets/1575670.js:1:17777)
    at async Promise.all (index 3)
    at async f (file:///snap/dreamtimetech/22/resources/app.asar/dist/assets/1575670.js:1:19692)
    at async file:///snap/dreamtimetech/22/resources/app.asar/dist/assets/1575670.js:1:20193
    at async t.a (file:///snap/dreamtimetech/22/resources/app.asar/dist/assets/1575670.js:1:20079)
    at async file:///snap/dreamtimetech/22/resources/app.asar/dist/assets/d662605.js:419:97170
```

**To Reproduce**
1. Install dreamtime via snap.
2. Type `dreamtimetech` in CLI.
3. Press the install button after going through the initial information and such.

**Expected behavior**
The components to be installed.

**Screenshots**

**Enviroment (please complete the following information):**
 - DreamTime Version: 1.6.4
 - OS: Arch Linux
 - RAM: 8GB
 - CPU: Intel i5-7200U (4) @ 3.1GHz 
 - GPU: Intel HD Integrated Graphics

**Comment by CraftCreeperDev** [comment]
Same issue for me. 

You can bypass this problem by downloading the relevant checkpoints files and pasting them into dreamtime/dreampower/checkpoints/, making the checkpoints folder if it doesn't exist.

**Comment by thorizer** [comment]
@CraftCreeperDev where I can download the relevant  checkpoints file ?

**Comment by CraftCreeperDev** [comment]
I found them here and there, quite a lot of searching involved actually. To[ save you the trouble](https://mega.nz/file/muJlTAJa#WnnTDoUZTgtXnmSNhyoqy75gDbgjtSCwJ_KZYs_Ve1Q).

**Comment by kolessios** [comment]
I have fixed this problem, please re-open DreamTime.

Notice: DreamTime is no longer in development and any problems may take months to fix, to visit our new project that generates higher quality nudes visit [SukebeZone+](https://www.sukebezone.com).
