### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by VityaSchel** [opendreamnet/dreamtime#331]
**Describe the bug**
I installed CUDA from NVIDIA website, and also installed 2 patches after that. Then I reinstalled DreamTime, but it seems to unable to locate CUDA on my computer.

**Screenshots**
![image](https://user-images.githubusercontent.com/59040542/193024716-d7d6fb71-a27c-4286-aba9-6f71ed8cc9e6.png)

**Enviroment (please complete the following information):**
 - DreamTime Version 1.6.4
 - OS: Windows 10
 - RAM: 8 GB
 - GPU: GeForce GTX 660 2 GB VRAM

**Comment by kolessios** [comment]
Your GPU does not meet the minimum requirements:

- [3.5 CUDA compute capability](https://developer.nvidia.com/cuda-gpus)
- 6 GB VRAM

Use CPU processing or upgrade your GPU.

**Comment by VityaSchel** [comment]
> Your GPU does not meet the minimum requirements:
> 
> * [3.5 CUDA compute capability](https://developer.nvidia.com/cuda-gpus)
> * 6 GB VRAM
> 
> Use CPU processing or upgrade your GPU.

Can I use CUDA with 3.0 compute capability somehow?

**Comment by kolessios** [comment]
You will need to compile [PyTorch](https://github.com/pytorch/pytorch#from-source) from source and then compile [DreamPower](https://github.com/opendreamnet/dreampower/blob/master/.github/workflows/build.yml) using the PyTorch you just compiled. A tedious and probably time-consuming process that does not guarantee that it will work correctly with your GPU.
